### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by DaniilKlyukin** [rustam-mansurov/cats#1]
Здесь был **Даниил** --->
https://github.com/rustam-mansurov/cats/blob/765d5953aa8a011eada6b5c7d018b66f5d9295ea/Externum_ballistics/Class1.cs#L3

**Comment by rustam-mansurov** [comment]
Hello (-_-)

**Comment by rustam-mansurov** [comment]
Всё нормально

**Comment by rustam-mansurov** [comment]
Всё было нормально
